languageCode = 'pl-PL'
title = 'PlayableElectronics'

baseurl = "/"
# Add it only if you keep the theme in the `themes` directory.
# Remove it if you use the theme as a remote Hugo Module.
theme = "terminal"
pagination.pagerSize = 5

# Required for Chroma and the custom syntax highlighting.
[markup.highlight]
  noClasses = false

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 4

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false

  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # whether to show a page's estimated reading time
  # readingTime = false # default

  # whether to show a table of contents
  # can be overridden in a page's front-matter
  # Toc = false # default

  # set title for the table of contents
  # can be overridden in a page's front-matter
  # TocTitle = "Table of Contents" # default

  # Set date/time format for posts
  # This will impact the date/time displayed on
  # index.html, the posts list page, and on posts themselves
  # This value can also be configured per-post on front matter
  # If you have any issues with the timezone rendering differently
  # than you expected, please ensure your timezone is correctly set
  # on your server.
  # This value can be customized according to Hugo documentation:
  # https://gohugo.io/functions/time/format/
  # Default value (no changes needed):
  # dateFormat = "2006-01-02"
  # Example format, with date, time, and timezone abbreviation:
  # dateFormat = "2006-01-02 3:04:06 PM MST"

[languages]
  [languages.pl]
    languageName = "Polski"
    title = "Terminal"

    [languages.pl.params]
      subtitle = "A simple, retro theme for Hugo"
      owner = ""
      keywords = ""
      copyright = ""
      menuMore = "Więcej"
      readMore = "Więcej"
      readOtherPosts = "Czytaj inne posty"
      newerPosts = "Nowsze posty"
      olderPosts = "Starsze posty"
      missingContentMessage = "Nie znaleziono strony..."
      missingBackButtonLabel = "Powrót do strony domowej"
      minuteReadingTime = "minuta czytania"
      words = "słowa"

      [languages.pl.params.logo]
        logoText = "PE"
        logoHomeLink = "/"
      [languages.pl.menu]
        [[languages.pl.menu.main]]
          identifier = "blog"
          name = "Blog"
          url = "/"
        [[languages.pl.menu.main]]
          identifier = "gear"
          name = "Sprzęt"
          url = "/gear"
        [[languages.pl.menu.main]]
          identifier = "about"
          name = "O mnie"
          url = "/about"
        [[languages.pl.menu.main]]
          identifier = "contact"
          name = "Kontakt"
          url = "/contact"
[caches]
  [caches.images]
    dir = ':cacheDir/images'
